name: "Todo to Issue"
author: "Mahdi Hosseinzadeh"
description: "Converts TODOs to Github issues"
branding:
  icon: "info"
  color: "green"
runs:
  using: "composite"
  steps:
    - id: main-step
      run: kotlin $GITHUB_ACTION_PATH/action.main.kts
      shell: bash
